// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEOmNO-cBmtsOUJ0wxiSvRyeHxhlznR0',
    appId: '1:424512087367:web:4ca7850517cdde38cf5862',
    messagingSenderId: '424512087367',
    projectId: 'fir-95593',
    authDomain: 'fir-95593.firebaseapp.com',
    storageBucket: 'fir-95593.firebasestorage.app',
    measurementId: 'G-Y30927VDV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7-aBrKHScVawDtyWXewbd93uw2H1liU',
    appId: '1:424512087367:android:939cdfd35f8dc788cf5862',
    messagingSenderId: '424512087367',
    projectId: 'fir-95593',
    storageBucket: 'fir-95593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDee98WZegF4sL8Zhz2soxVvAVxDNGZMo',
    appId: '1:424512087367:ios:186a3a792de2ed8dcf5862',
    messagingSenderId: '424512087367',
    projectId: 'fir-95593',
    storageBucket: 'fir-95593.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDee98WZegF4sL8Zhz2soxVvAVxDNGZMo',
    appId: '1:424512087367:ios:186a3a792de2ed8dcf5862',
    messagingSenderId: '424512087367',
    projectId: 'fir-95593',
    storageBucket: 'fir-95593.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEOmNO-cBmtsOUJ0wxiSvRyeHxhlznR0',
    appId: '1:424512087367:web:a9bd1a248672216ecf5862',
    messagingSenderId: '424512087367',
    projectId: 'fir-95593',
    authDomain: 'fir-95593.firebaseapp.com',
    storageBucket: 'fir-95593.firebasestorage.app',
    measurementId: 'G-K7ZQCFH0DS',
  );
}
